version: '3'

tasks:
  desc: "build scratchpad"
  build:
    cmds:
      - mkdir -p dist/debug
      - go build -o dist/debug/scratchpad .

  run:
    desc: "run scratchpad"
    deps:
      - build
    cmds:
      - ./dist/debug/scratchpad {{.CLI_ARGS}}

  example:
    desc: "example"
    deps:
      - build
    cmd: |
        ./dist/debug/scratchpad play \
          -a ./audio/aaah-fresh/envs.js