version: '3'

tasks:
  desc: "build scratchpad"
  build:
    cmds:
      - mkdir -p dist/debug
      - go build -o dist/debug/scratchpad .

  run:
    desc: "run scratchpad"
    deps:
      - build
    cmds:
      - ./dist/debug/scratchpad {{.CLI_ARGS}}

  example-orc-1:
    desc: "example"
    deps:
      - build
    cmd: |
        ./dist/debug/scratchpad play \
          -a ./audio/orchectra-hit/figure-1.auto.txt \
          ./audio/orchectra-hit/822403__astro_denticle__gm-orch-hit-sinfonietta-op.wav

  example-voice-see-you-linear:
    desc: "example"
    deps:
      - build
    cmd: |
        ./dist/debug/scratchpad play \
          -a ./audio/linear.auto.txt \
          ./audio/voice-see-you/727512__voiceoverneil__see-you-next-time-neil-williams-male-voice-over-artist.wav

  example-voice-see-you-1:
    desc: "example"
    deps:
      - build
    cmd: |
        ./dist/debug/scratchpad play \
          -a ./audio/voice-see-you/figure-1.auto.txt \
          ./audio/voice-see-you/727512__voiceoverneil__see-you-next-time-neil-williams-male-voice-over-artist.wav

  example-voice-see-you-2:
    desc: "example"
    deps:
      - build
    cmd: |
        ./dist/debug/scratchpad play \
          -a ./audio/voice-see-you/figure-2.auto.txt \
          ./audio/voice-see-you/727512__voiceoverneil__see-you-next-time-neil-williams-male-voice-over-artist.wav


# audio/orchestra-low-hit/414343__malocculsion__malocculsion_orchestrahell1.wav

  example-orchestra-low-hit-1:
    desc: "example"
    deps:
      - build
    cmd: |
        ./dist/debug/scratchpad play \
          -a ./audio/orchestra-low-hit/figure-1.auto.txt \
          ./audio/orchestra-low-hit/414343__malocculsion__malocculsion_orchestrahell1.wav

  example-orchestra-low-hit-2:
    desc: "example"
    deps:
      - build
    cmd: |
        ./dist/debug/scratchpad play \
          -a ./audio/orchestra-low-hit/figure-2.auto.txt \
          ./audio/orchestra-low-hit/414343__malocculsion__malocculsion_orchestrahell1.wav