version: '3'

tasks:
  build:
    cmds:
      - mkdir -p dist/debug
      - go build -o dist/debug/scratchpad .

  run:
    deps:
      - build
    cmds:
      - ./dist/debug/scratchpad {{.CLI_ARGS}}
