// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // ␚, reduce: Lines
			nil,       // empty
			reduce(2), // nl, reduce: Lines
			reduce(2), // bpm, reduce: Lines
			reduce(2), // +, reduce: Lines
			reduce(2), // -, reduce: Lines
			reduce(2), // frac, reduce: Lines
			reduce(2), // float, reduce: Lines
			reduce(2), // int, reduce: Lines
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // ␚
			nil,          // empty
			nil,          // nl
			nil,          // bpm
			nil,          // +
			nil,          // -
			nil,          // frac
			nil,          // float
			nil,          // int
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // ␚, reduce: Program
			nil,       // empty
			shift(4),  // nl
			shift(8),  // bpm
			shift(11), // +
			shift(12), // -
			shift(13), // frac
			shift(14), // float
			shift(15), // int
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // ␚, reduce: Lines
			nil,       // empty
			reduce(3), // nl, reduce: Lines
			reduce(3), // bpm, reduce: Lines
			reduce(3), // +, reduce: Lines
			reduce(3), // -, reduce: Lines
			reduce(3), // frac, reduce: Lines
			reduce(3), // float, reduce: Lines
			reduce(3), // int, reduce: Lines
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // ␚, reduce: Line
			nil,       // empty
			reduce(4), // nl, reduce: Line
			reduce(4), // bpm, reduce: Line
			reduce(4), // +, reduce: Line
			reduce(4), // -, reduce: Line
			reduce(4), // frac, reduce: Line
			reduce(4), // float, reduce: Line
			reduce(4), // int, reduce: Line
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(16), // nl
			nil,       // bpm
			nil,       // +
			nil,       // -
			nil,       // frac
			nil,       // float
			nil,       // int
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			reduce(6), // nl, reduce: Stmt
			nil,       // bpm
			nil,       // +
			nil,       // -
			nil,       // frac
			nil,       // float
			nil,       // int
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			reduce(7), // nl, reduce: Stmt
			nil,       // bpm
			nil,       // +
			nil,       // -
			nil,       // frac
			nil,       // float
			nil,       // int
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // nl
			nil,       // bpm
			nil,       // +
			nil,       // -
			shift(18), // frac
			shift(19), // float
			shift(20), // int
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(15), // nl, reduce: Dh
			nil,        // bpm
			nil,        // +
			nil,        // -
			reduce(15), // frac, reduce: Dh
			reduce(15), // float, reduce: Dh
			reduce(15), // int, reduce: Dh
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			reduce(9), // nl, reduce: MoveStmt
			nil,       // bpm
			nil,       // +
			nil,       // -
			shift(18), // frac
			shift(19), // float
			shift(20), // int
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(11), // nl, reduce: Dh
			nil,        // bpm
			nil,        // +
			nil,        // -
			shift(13),  // frac
			shift(14),  // float
			shift(15),  // int
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(12), // nl, reduce: Dh
			nil,        // bpm
			nil,        // +
			nil,        // -
			shift(13),  // frac
			shift(14),  // float
			shift(15),  // int
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(17), // nl, reduce: Number
			nil,        // bpm
			nil,        // +
			nil,        // -
			reduce(17), // frac, reduce: Number
			reduce(17), // float, reduce: Number
			reduce(17), // int, reduce: Number
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(18), // nl, reduce: Number
			nil,        // bpm
			nil,        // +
			nil,        // -
			reduce(18), // frac, reduce: Number
			reduce(18), // float, reduce: Number
			reduce(18), // int, reduce: Number
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(19), // nl, reduce: Number
			nil,        // bpm
			nil,        // +
			nil,        // -
			reduce(19), // frac, reduce: Number
			reduce(19), // float, reduce: Number
			reduce(19), // int, reduce: Number
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // ␚, reduce: Line
			nil,       // empty
			reduce(5), // nl, reduce: Line
			reduce(5), // bpm, reduce: Line
			reduce(5), // +, reduce: Line
			reduce(5), // -, reduce: Line
			reduce(5), // frac, reduce: Line
			reduce(5), // float, reduce: Line
			reduce(5), // int, reduce: Line
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			reduce(8), // nl, reduce: BpmStmt
			nil,       // bpm
			nil,       // +
			nil,       // -
			nil,       // frac
			nil,       // float
			nil,       // int
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(17), // nl, reduce: Number
			nil,        // bpm
			nil,        // +
			nil,        // -
			nil,        // frac
			nil,        // float
			nil,        // int
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(18), // nl, reduce: Number
			nil,        // bpm
			nil,        // +
			nil,        // -
			nil,        // frac
			nil,        // float
			nil,        // int
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(19), // nl, reduce: Number
			nil,        // bpm
			nil,        // +
			nil,        // -
			nil,        // frac
			nil,        // float
			nil,        // int
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(16), // nl, reduce: Dt
			nil,        // bpm
			nil,        // +
			nil,        // -
			nil,        // frac
			nil,        // float
			nil,        // int
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(10), // nl, reduce: MoveStmt
			nil,        // bpm
			nil,        // +
			nil,        // -
			nil,        // frac
			nil,        // float
			nil,        // int
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(13), // nl, reduce: Dh
			nil,        // bpm
			nil,        // +
			nil,        // -
			reduce(13), // frac, reduce: Dh
			reduce(13), // float, reduce: Dh
			reduce(13), // int, reduce: Dh
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(14), // nl, reduce: Dh
			nil,        // bpm
			nil,        // +
			nil,        // -
			reduce(14), // frac, reduce: Dh
			reduce(14), // float, reduce: Dh
			reduce(14), // int, reduce: Dh
		},
	},
}
