// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 10

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Program
		2,  // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Program
		-1, // Lines
		3,  // Line
		5,  // Stmt
		6,  // BpmStmt
		7,  // MoveStmt
		10, // Dh
		-1, // Dt
		9,  // Number
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S5
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S6
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S7
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S8
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		17, // Number
	},
	gotoRow{ // S9
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S10
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		22, // Dt
		21, // Number
	},
	gotoRow{ // S11
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		23, // Number
	},
	gotoRow{ // S12
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		24, // Number
	},
	gotoRow{ // S13
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S14
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S15
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S16
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S17
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S18
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S19
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S20
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S21
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S22
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S23
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
	gotoRow{ // S24
		-1, // S'
		-1, // Program
		-1, // Lines
		-1, // Line
		-1, // Stmt
		-1, // BpmStmt
		-1, // MoveStmt
		-1, // Dh
		-1, // Dt
		-1, // Number
	},
}
