// Code generated by gocc; DO NOT EDIT.

package parser

import (
  "strconv"
  "strings"

  ast "github.com/fruity-loozrz/go-scratchpad/internal/automationast"
  "github.com/fruity-loozrz/go-scratchpad/internal/automationparser/token"
)

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib, interface{}) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : Program	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Program : Lines	<< ast.Program{Lines: X[0].([]ast.Stmt)}, nil >>`,
		Id:         "Program",
		NTType:     1,
		Index:      1,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.Program{Lines: X[0].([]ast.Stmt)}, nil
		},
	},
	ProdTabEntry{
		String: `Lines : "empty"	<< []ast.Stmt{}, nil >>`,
		Id:         "Lines",
		NTType:     2,
		Index:      2,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return []ast.Stmt{}, nil
		},
	},
	ProdTabEntry{
		String: `Lines : Lines Line	<< append(X[0].([]ast.Stmt), X[1].([]ast.Stmt)...), nil >>`,
		Id:         "Lines",
		NTType:     2,
		Index:      3,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return append(X[0].([]ast.Stmt), X[1].([]ast.Stmt)...), nil
		},
	},
	ProdTabEntry{
		String: `Line : nl	<< []ast.Stmt{}, nil >>`,
		Id:         "Line",
		NTType:     3,
		Index:      4,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return []ast.Stmt{}, nil
		},
	},
	ProdTabEntry{
		String: `Line : Stmt nl	<< []ast.Stmt{X[0].(ast.Stmt)}, nil >>`,
		Id:         "Line",
		NTType:     3,
		Index:      5,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return []ast.Stmt{X[0].(ast.Stmt)}, nil
		},
	},
	ProdTabEntry{
		String: `Stmt : BpmStmt	<<  >>`,
		Id:         "Stmt",
		NTType:     4,
		Index:      6,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Stmt : MoveStmt	<<  >>`,
		Id:         "Stmt",
		NTType:     4,
		Index:      7,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `BpmStmt : "bpm" Number	<< ast.BPM{Value: X[1].(ast.Number)}, nil >>`,
		Id:         "BpmStmt",
		NTType:     5,
		Index:      8,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.BPM{Value: X[1].(ast.Number)}, nil
		},
	},
	ProdTabEntry{
		String: `MoveStmt : Dh	<< ast.Move{DH: X[0].(ast.Number), DT: nil}, nil >>`,
		Id:         "MoveStmt",
		NTType:     6,
		Index:      9,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.Move{DH: X[0].(ast.Number), DT: nil}, nil
		},
	},
	ProdTabEntry{
		String: `MoveStmt : Dh Dt	<< func() (interface{}, error) {
          dt := X[1].(ast.Number)
          return ast.Move{DH: X[0].(ast.Number), DT: &dt}, nil
      }() >>`,
		Id:         "MoveStmt",
		NTType:     6,
		Index:      10,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return func() (interface{}, error) {
          dt := X[1].(ast.Number)
          return ast.Move{DH: X[0].(ast.Number), DT: &dt}, nil
      }()
		},
	},
	ProdTabEntry{
		String: `Dh : "+"	<< ast.Number{Kind:"int", Int:1}, nil >>`,
		Id:         "Dh",
		NTType:     7,
		Index:      11,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.Number{Kind:"int", Int:1}, nil
		},
	},
	ProdTabEntry{
		String: `Dh : "-"	<< ast.Number{Kind:"int", Int:-1}, nil >>`,
		Id:         "Dh",
		NTType:     7,
		Index:      12,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return ast.Number{Kind:"int", Int:-1}, nil
		},
	},
	ProdTabEntry{
		String: `Dh : "+" Number	<< func() (interface{}, error) {
          n := X[1].(ast.Number)
          // применяем знак к Number
          switch n.Kind {
          case "int":
            n.Int = +n.Int
          case "float":
            n.Float = +n.Float
          case "frac":
            n.Num = +n.Num
          }
          return n, nil
      }() >>`,
		Id:         "Dh",
		NTType:     7,
		Index:      13,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return func() (interface{}, error) {
          n := X[1].(ast.Number)
          // применяем знак к Number
          switch n.Kind {
          case "int":
            n.Int = +n.Int
          case "float":
            n.Float = +n.Float
          case "frac":
            n.Num = +n.Num
          }
          return n, nil
      }()
		},
	},
	ProdTabEntry{
		String: `Dh : "-" Number	<< func() (interface{}, error) {
          n := X[1].(ast.Number)
          switch n.Kind {
          case "int":
            n.Int = -n.Int
          case "float":
            n.Float = -n.Float
          case "frac":
            n.Num = -n.Num
          }
          return n, nil
      }() >>`,
		Id:         "Dh",
		NTType:     7,
		Index:      14,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return func() (interface{}, error) {
          n := X[1].(ast.Number)
          switch n.Kind {
          case "int":
            n.Int = -n.Int
          case "float":
            n.Float = -n.Float
          case "frac":
            n.Num = -n.Num
          }
          return n, nil
      }()
		},
	},
	ProdTabEntry{
		String: `Dh : Number	<<  >>`,
		Id:         "Dh",
		NTType:     7,
		Index:      15,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Dt : Number	<< X[0], nil >>`,
		Id:         "Dt",
		NTType:     8,
		Index:      16,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Number : frac	<< func() (interface{}, error) {
          lit := string(X[0].(*token.Token).Lit)
          parts := strings.SplitN(lit, "/", 2)
          a, err := strconv.ParseInt(parts[0], 10, 64)
          if err != nil { return nil, err }
          b, err := strconv.ParseInt(parts[1], 10, 64)
          if err != nil { return nil, err }
          return ast.Number{Kind:"frac", Num:a, Den:b}, nil
      }() >>`,
		Id:         "Number",
		NTType:     9,
		Index:      17,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return func() (interface{}, error) {
          lit := string(X[0].(*token.Token).Lit)
          parts := strings.SplitN(lit, "/", 2)
          a, err := strconv.ParseInt(parts[0], 10, 64)
          if err != nil { return nil, err }
          b, err := strconv.ParseInt(parts[1], 10, 64)
          if err != nil { return nil, err }
          return ast.Number{Kind:"frac", Num:a, Den:b}, nil
      }()
		},
	},
	ProdTabEntry{
		String: `Number : float	<< func() (interface{}, error) {
          lit := string(X[0].(*token.Token).Lit)
          f, err := strconv.ParseFloat(lit, 64)
          if err != nil { return nil, err }
          return ast.Number{Kind:"float", Float:f}, nil
      }() >>`,
		Id:         "Number",
		NTType:     9,
		Index:      18,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return func() (interface{}, error) {
          lit := string(X[0].(*token.Token).Lit)
          f, err := strconv.ParseFloat(lit, 64)
          if err != nil { return nil, err }
          return ast.Number{Kind:"float", Float:f}, nil
      }()
		},
	},
	ProdTabEntry{
		String: `Number : int	<< func() (interface{}, error) {
          lit := string(X[0].(*token.Token).Lit)
          v, err := strconv.ParseInt(lit, 10, 64)
          if err != nil { return nil, err }
          return ast.Number{Kind:"int", Int:v}, nil
      }() >>`,
		Id:         "Number",
		NTType:     9,
		Index:      19,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return func() (interface{}, error) {
          lit := string(X[0].(*token.Token).Lit)
          v, err := strconv.ParseInt(lit, 10, 64)
          if err != nil { return nil, err }
          return ast.Number{Kind:"int", Int:v}, nil
      }()
		},
	},
}
