// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 2
		case r == 13: // ['\r','\r']
			return 3
		case r == 32: // [' ',' ']
			return 1
		case r == 35: // ['#','#']
			return 4
		case r == 43: // ['+','+']
			return 5
		case r == 45: // ['-','-']
			return 6
		case 48 <= r && r <= 57: // ['0','9']
			return 7
		case r == 98: // ['b','b']
			return 8
		case r == 101: // ['e','e']
			return 9
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 2
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		case 0 <= r && r <= 9: // [\u0000,'\t']
			return 10
		case 11 <= r && r <= 12: // ['\v','\f']
			return 10
		case 14 <= r && r <= 65535: // [\u000e,\uffff]
			return 10
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 11
		case r == 47: // ['/','/']
			return 12
		case 48 <= r && r <= 57: // ['0','9']
			return 7
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case r == 112: // ['p','p']
			return 13
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 109: // ['m','m']
			return 14
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case 0 <= r && r <= 9: // [\u0000,'\t']
			return 10
		case 11 <= r && r <= 12: // ['\v','\f']
			return 10
		case 14 <= r && r <= 65535: // [\u000e,\uffff]
			return 10
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 16
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 109: // ['m','m']
			return 17
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 112: // ['p','p']
			return 18
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 15
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 16
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 116: // ['t','t']
			return 19
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 121: // ['y','y']
			return 20
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		}
		return NoState
	},
}
